#!/usr/bin/env bash
# kport promote
#
# Moves a generated/ pacscript skeleton to packages/ for production use.
# Validates the skeleton before promoting and refuses if required fields
# are missing or still contain placeholder values.
#
# Usage: kport promote [options] <pkgname>
#
# Options:
#   --dry-run    Validate and show what would happen without moving files
#   --force      Overwrite existing packages/ entry if present
#   --help

set -uo pipefail

# ── Parse args ────────────────────────────────────────────────────────────────

DRY_RUN=false
FORCE=false
PKGNAME=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true;  shift ;;
    --force)   FORCE=true;    shift ;;
    --help|-h)
      sed -n '2,/^$/p' "${BASH_SOURCE[0]}" | grep '^#' | sed 's/^# \?//'
      exit 0 ;;
    -*) kport_die "Unknown option: $1" ;;
    *)  PKGNAME="$1"; shift ;;
  esac
done

[[ -z "$PKGNAME" ]] && kport_die "Usage: kport promote <pkgname>"

# ── Find generated pacscript ──────────────────────────────────────────────────

gen_pacscript=$(find "$KPORT_GENERATED_DIR" -name "${PKGNAME}.pacscript" 2>/dev/null | head -1)
[[ -z "$gen_pacscript" ]] && kport_die "No generated pacscript found for: ${PKGNAME}"

kport_info "Found: ${gen_pacscript}"

# ── Validate ──────────────────────────────────────────────────────────────────

errors=0

_check() {
  local label="$1" value="$2" bad_pattern="${3:-}"
  if [[ -z "$value" ]]; then
    kport_error "  MISSING: ${label}"
    (( errors++ )) || true
    return
  fi
  if [[ -n "$bad_pattern" && "$value" == *"$bad_pattern"* ]]; then
    kport_error "  PLACEHOLDER: ${label} = '${value}'"
    (( errors++ )) || true
    return
  fi
  kport_verbose "  OK: ${label} = ${value}"
}

kport_header "Validating ${PKGNAME}"

pkgname=$(kport_pacscript_var  "$gen_pacscript" pkgname)
pkgver=$(kport_pacscript_var   "$gen_pacscript" pkgver)
pkgdesc=$(kport_pacscript_var  "$gen_pacscript" pkgdesc)
url=$(kport_pacscript_var      "$gen_pacscript" url)
category=$(kport_pacscript_var "$gen_pacscript" KCATEGORY)

_check "pkgname"   "$pkgname"
_check "pkgver"    "$pkgver"   "0.0.0"
_check "pkgdesc"   "$pkgdesc"
_check "url"       "$url"
_check "KCATEGORY" "$category"

# Check sha256sums — must not be SKIP
mapfile -t shasums < <(kport_pacscript_array "$gen_pacscript" sha256sums)
for sum in "${shasums[@]}"; do
  if [[ "$sum" == "SKIP" ]]; then
    kport_warn "  sha256sums contains SKIP — replace with actual checksum before promoting"
    # Warning only, not a hard error — reviewer may accept SKIP during development
  fi
done

# Check depends is not empty with only a comment
local depends_block
depends_block=$(grep -A5 "^depends=(" "$gen_pacscript" 2>/dev/null || true)
if echo "$depends_block" | grep -q "TODO\|populate after"; then
  kport_warn "  depends() contains TODO comment — verify runtime deps before promoting"
fi

if [[ "$errors" -gt 0 ]]; then
  kport_error "${errors} validation error(s) — fix before promoting"
  exit 1
fi

kport_info "Validation passed."

# ── Determine destination ─────────────────────────────────────────────────────

dest_dir="${KPORT_PACKAGES_DIR}/${category}/${pkgname}"
dest_file="${dest_dir}/${pkgname}.pacscript"

if [[ -f "$dest_file" && "$FORCE" != "true" ]]; then
  kport_die "${dest_file} already exists. Use --force to overwrite."
fi

# ── Promote ───────────────────────────────────────────────────────────────────

if [[ "$DRY_RUN" == "true" ]]; then
  kport_info "[dry-run] would move:"
  kport_kv "From" "$gen_pacscript"
  kport_kv "To"   "$dest_file"
  exit 0
fi

mkdir -p "$dest_dir"
cp "$gen_pacscript" "$dest_file"

# Update the header comment to reflect promotion
sed -i "s|# Auto-generated by generate-pacscripts.sh.*|# Promoted from generated/ — review and test before merging to main|" \
  "$dest_file" 2>/dev/null || true

# Remove the generated source
rm -f "$gen_pacscript"
# Remove empty generated dir
rmdir "$(dirname "$gen_pacscript")" 2>/dev/null || true

kport_info "${C_GREEN}✔${C_RESET} Promoted ${pkgname} → ${dest_file}"
echo ""
kport_info "Next steps:"
echo "  1. Review ${dest_file}"
echo "  2. Replace SKIP sha256sums with actual checksums"
echo "  3. Verify depends() runtime deps"
echo "  4. Test build: kport install ${pkgname}"
echo "  5. Commit and open a PR"
